/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is checked in here so
// TypeScript can resolve Next types before the first local build.
